export const DB_MONGO_HOST = 'DB_MONGO_HOST';
export const DB_MONGO_PORT = 'DB_MONGO_PORT';
export const DB_MONGO_DB = 'DB_MONGO_DB';
export const DB_MONGO_USER = 'DB_MONGO_USER';
export const DB_MONGO_PASSWORD = 'DB_MONGO_PASSWORD';
export const DB_MONGO_CONNECTION = 'DB_MONGO_CONNECTION';
